Areas/ContactDetails/Models/ContactDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcApplication1.Areas.ContactDetails.Models
{
    public class ContactDetails
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Address HomeAddress { get; set; }
        public Phone HomePhone { get; set; }
        public Phone CellPhone { get; set; }
    }

    public class Phone
    {
        public string CountryCode { get; set; }
        public string AreaCode { get; set; }
        public string PhoneNumber { get; set; }
    }

    public class Address
    {
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
    }
}

Areas/ContactDetails/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Areas.ContactDetails.Controllers
{
    public class ManagementController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }        

        [HttpPost]
        public ActionResult Index(ContactDetails.Models.ContactDetails details)
        {
            return View(details);
        }        
    }
}

Areas/ContactDetails/Views/Management/Index.cshtml
@model MvcApplication1.Areas.ContactDetails.Models.ContactDetails

@{
    ViewBag.Title = "Index";
}
@using (Html.BeginForm())
{
    <fieldset>
        <legend>Contact Details</legend>
        <table>
            <tr>
                <td>@Html.LabelFor(model => model.FirstName)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.FirstName)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.LastName)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.LastName)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Email)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.Email)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.HomePhone)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.HomePhone.CountryCode)</td>
                <td>@Html.EditorFor(model => model.HomePhone.AreaCode)</td>
                <td>@Html.EditorFor(model => model.HomePhone.PhoneNumber)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.CellPhone)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.CellPhone.CountryCode)</td>
                <td>@Html.EditorFor(model => model.CellPhone.AreaCode)</td>
                <td>@Html.EditorFor(model => model.CellPhone.PhoneNumber)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.HomeAddress.Line1)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.HomeAddress.Line1)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.HomeAddress.Line2)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.HomeAddress.Line2)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.HomeAddress.Line3)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.HomeAddress.Line3)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.HomeAddress.City)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.HomeAddress.City)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.HomeAddress.Province)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.HomeAddress.Province)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.HomeAddress.PostalCode)</td>
            </tr>
            <tr>
                <td>@Html.EditorFor(model => model.HomeAddress.PostalCode)</td>
            </tr>
        </table>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<nav>@Html.ActionLink("Back To List", "Index", "Management")</nav>